version: '3'
services:
  app:
    build: ./myapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file: ./config/myapp/.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
    - ./myapp:/myapp
    ports:
    - "3000:3000"
    - "3500:3500"
    links:
    - db
  
  db:
    build: ./mysql
    env_file: ./config/mysql/.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/logs/:/var/log/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

